FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/
COPY app /app/app
COPY config.py /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD celery -A app.celery worker --loglevel=info
